In [16]:
import sys

import torch
from torch.nn import Parameter
import torch.nn as nn
import torch.nn.functional as F

import syft as sy
hook = sy.TorchHook(torch)

torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [17]:
x = torch.tensor([1,2,3,4,5])
y = x + x
print(y)

tensor([ 2,  4,  6,  8, 10])


In [18]:
bob = sy.VirtualWorker(hook, id="bob")

In [12]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([1,1,1,1,1])

In [13]:
x_ptr = x.send(bob)
y_ptr = y.send(bob)

In [14]:
x_ptr

(Wrapper)>[PointerTensor | me:7852760722 -> bob:9036778258]

In [15]:
bob._objects

{83813622159: tensor([1, 2, 3, 4, 5]),
 9036778258: tensor([1, 2, 3, 4, 5]),
 80990476753: tensor([1, 1, 1, 1, 1])}

In [9]:
z = x_ptr + x_ptr

In [10]:
z

(Wrapper)>[PointerTensor | me:85895451406 -> bob:62945849818]

In [11]:
bob._objects

{94723068855: tensor([1, 2, 3, 4, 5]),
 42213798136: tensor([1, 1, 1, 1, 1]),
 62945849818: tensor([ 2,  4,  6,  8, 10])}

In [12]:
x_ptr

(Wrapper)>[PointerTensor | me:99300588281 -> bob:94723068855]

In [13]:
x_ptr.location

<VirtualWorker id:bob #objects:3>

In [14]:
bob

<VirtualWorker id:bob #objects:3>

In [15]:
bob == x_ptr.location

True

In [16]:
x_ptr.id_at_location

94723068855

In [17]:
x_ptr.owner

<VirtualWorker id:me #objects:0>

In [18]:
me = sy.local_worker
me

<VirtualWorker id:me #objects:0>

In [19]:
me == x_ptr.owner

True

In [20]:
x_ptr

(Wrapper)>[PointerTensor | me:99300588281 -> bob:94723068855]

In [21]:
x_ptr.get()

tensor([1, 2, 3, 4, 5])

In [22]:
y_ptr

(Wrapper)>[PointerTensor | me:95030386240 -> bob:42213798136]

In [23]:
y_ptr.get()

tensor([1, 1, 1, 1, 1])

In [24]:
z.get()

tensor([ 2,  4,  6,  8, 10])

In [25]:

bob._objects

{}